name: git-tag-main-push
run-name: ${{ github.actor }} is creating a deployment tag
on:
  push:
    branches:
      - 'main'
jobs:
  create-prod-tag:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - run: |
          DATETIME=`date +%Y%m%d%H%M`
          BRANCHNAME=${{ github.head_ref || github.ref_name }}
          git tag prod_${BRANCHNAME}_$DATETIME
          git push origin tag prod_${BRANCHNAME}_$DATETIME
